### ISSUE TITLE
Getting error message “AssertionError: View function mapping is overwriting an existing endpoint function

### ISSUE THREAD

**Issue by jcleung5549** [DMTF/Redfish-Interface-Emulator#26]
Accessing /redfish/v1/EventService produces the expected output, but causes an error message. 

Running in Redfish mode
Traceback (most recent call last):
  File "C:\Users\ddon\Documents\EmRf\api_emulator\redfish\EventService_api.py", line 33, in __init__
    g.api.add_resource(SubscriptionCollectionAPI,   '/redfish/v1/EventService/Subscriptions')
  File "C:\Users\ddon\Documents\EmRf\lib\site-packages\flask_restful\__init__.py", line 404, in add_resource
    self._register_view(self.app, resource, *urls, **kwargs)
  File "C:\Users\ddon\Documents\EmRf\lib\site-packages\flask_restful\__init__.py", line 470, in _register_view
    app.add_url_rule(rule, view_func=resource_func, **kwargs)
  File "C:\Users\ddon\Documents\EmRf\lib\site-packages\flask\app.py", line 64, in wrapper_func
    return f(self, *args, **kwargs)
  File "C:\Users\ddon\Documents\EmRf\lib\site-packages\flask\app.py", line 1051, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: subscriptioncollectionapi

**Comment by mraineri** [comment]
Fixed in latest PR
