### ISSUE TITLE
GET on EventService works, but causes an error

### ISSUE THREAD

**Issue by ddeel** [DMTF/Redfish-Interface-Emulator#29]
Running the unmodified code from master, the emulator outputs an error on the console whenever EventService is accessed with a normal GET:

    GET http://localhost:5000/redfish/v1/EventService

The Restlet Client receives a "200 OK" result and an OK-seeming Body from this GET, but the following traceback and error message appears on the console:

Traceback (most recent call last):
  File "C:\Users\ddon\Documents\EmRf\api_emulator\redfish\EventService_api.py", line 33, in __init__
    g.api.add_resource(SubscriptionCollectionAPI,   '/redfish/v1/EventService/Subscriptions')
  File "C:\Users\ddon\Documents\EmRf\lib\site-packages\flask_restful\__init__.py", line 404, in add_resource
    self._register_view(self.app, resource, *urls, **kwargs)
  File "C:\Users\ddon\Documents\EmRf\lib\site-packages\flask_restful\__init__.py", line 470, in _register_view
    app.add_url_rule(rule, view_func=resource_func, **kwargs)
  File "C:\Users\ddon\Documents\EmRf\lib\site-packages\flask\app.py", line 64, in wrapper_func
    return f(self, *args, **kwargs)
  File "C:\Users\ddon\Documents\EmRf\lib\site-packages\flask\app.py", line 1051, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: subscriptioncollectionapi

**Comment by ddeel** [comment]
This Issue was resolved by pull request #46 , and is no longer a problem.
