### ISSUE TITLE
Errors in error handling for getting invalid resource

### ISSUE THREAD

**Issue by stmcginnis** [DMTF/Redfish-Interface-Emulator#52]
If a request to a resource is made that is invalid or no longer there, looking up the resource will hit a KeyError. This should be fine, but the error handling for this attempts to get the exception information by accessing the 'message' property. Not all exceptions have a message property, including KeyError, so this causes the following:

Traceback (most recent call last):
  File "emulator.py", line 180, in get
    config = self.get_configuration(resource_manager, path)
  File "emulator.py", line 282, in get_configuration
    raise PathError("Resource not found: " + str(e.message))
AttributeError: 'KeyError' object has no attribute 'message'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/smcginnis/repos/SNIA/Swordfish/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/smcginnis/repos/SNIA/Swordfish/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/smcginnis/repos/SNIA/Swordfish/venv/lib/python3.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/smcginnis/repos/SNIA/Swordfish/venv/lib/python3.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/smcginnis/repos/SNIA/Swordfish/venv/lib/python3.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "emulator.py", line 189, in get
    resp = INTERNAL_ERROR_Get
NameError: name 'INTERNAL_ERROR_Get' is not defined

In addition to the e.message issue, there appears to be a typo with INTERNAL_ERROR_Get. We only have an INTERNAL_ERROR variable defined, and it would appear this is what is supposed to be used there.

**Comment by mraineri** [comment]
Closing; fixed in latest PR
